const mybookings = [
  {
    "Provider ID": "020001",
    "Hospital Name": "PROVIDENCE ALASKA MEDICAL CENTER",
    Address: "3200 PROVIDENCE DRIVE",
    City: "ANCHORAGE",
    State: "Alaska",
    "ZIP Code": 99508,
    "County Name": "ANCHORAGE",
    "Phone Number": 9075622211,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Church",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 3,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Above the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Same as the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "020006",
    "Hospital Name": "MAT-SU REGIONAL MEDICAL CENTER",
    Address: "2500 SOUTH WOODWORTH LOOP",
    City: "PALMER",
    State: "Alaska",
    "ZIP Code": 99645,
    "County Name": "MATANUSKA SUSITNA",
    "Phone Number": 9078616000,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Private",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 3,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Same as the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Same as the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Same as the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "020008",
    "Hospital Name": "BARTLETT REGIONAL HOSPITAL",
    Address: "3260 HOSPITAL DR",
    City: "JUNEAU",
    State: "Alaska",
    "ZIP Code": 99801,
    "County Name": "JUNEAU",
    "Phone Number": 9077968900,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Government - Local",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 3,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Same as the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Same as the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Same as the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Same as the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison": "Not Available",
    "Efficient use of medical imaging national comparison footnote":
      "Results are not available for this reporting period",
  },
  {
    "Provider ID": "020012",
    "Hospital Name": "FAIRBANKS MEMORIAL HOSPITAL",
    Address: "1650 COWLES STREET",
    City: "FAIRBANKS",
    State: "Alaska",
    "ZIP Code": 99701,
    "County Name": "FAIRBANKS NORTH STAR",
    "Phone Number": 9074528181,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Other",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 3,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Above the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Above the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Same as the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "020017",
    "Hospital Name": "ALASKA REGIONAL HOSPITAL",
    Address: "2801 DEBARR ROAD",
    City: "ANCHORAGE",
    State: "Alaska",
    "ZIP Code": 99508,
    "County Name": "ANCHORAGE",
    "Phone Number": 9072761131,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Proprietary",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 5,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Above the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Same as the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Same as the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison": "Not Available",
    "Efficient use of medical imaging national comparison footnote":
      "Results are not available for this reporting period",
  },
  {
    "Provider ID": "020018",
    "Hospital Name": "YUKON KUSKOKWIM DELTA REG HOSPITAL",
    Address: "PO BOX 287",
    City: "BETHEL",
    State: "Alaska",
    "ZIP Code": 99559,
    "County Name": "BETHEL",
    "Phone Number": 9075436300,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Tribal",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 4,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote":
      "This hospital�s star rating only includes data reported on inpatient services",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Not Available",
    "Safety of care national comparison footnote":
      "Results are not available for this reporting period",
    "Readmission national comparison": "Same as the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Not Available",
    "Effectiveness of care national comparison footnote":
      "Results are not available for this reporting period",
    "Timeliness of care national comparison": "Not Available",
    "Timeliness of care national comparison footnote":
      "Results are not available for this reporting period",
    "Efficient use of medical imaging national comparison": "Not Available",
    "Efficient use of medical imaging national comparison footnote":
      "Results are not available for this reporting period",
  },
  {
    "Provider ID": "020026",
    "Hospital Name": "ALASKA NATIVE MEDICAL CENTER",
    Address: "4315 DIPLOMACY DR",
    City: "ANCHORAGE",
    State: "Alaska",
    "ZIP Code": 99508,
    "County Name": "ANCHORAGE",
    "Phone Number": 9075632662,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Government - Federal",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 2,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote":
      "This hospital�s star rating only includes data reported on inpatient services",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Same as the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Below the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Not Available",
    "Timeliness of care national comparison footnote":
      "Results are not available for this reporting period",
    "Efficient use of medical imaging national comparison": "Not Available",
    "Efficient use of medical imaging national comparison footnote":
      "Results are not available for this reporting period",
  },
  {
    "Provider ID": "021311",
    "Hospital Name": "PEACEHEALTH KETCHIKAN MEDICAL CENTER",
    Address: "3100 TONGASS AVENUE",
    City: "KETCHIKAN",
    State: "Alaska",
    "ZIP Code": 99901,
    "County Name": "KETCHIKAN GATEWAY",
    "Phone Number": 9072255171,
    "Hospital Type": "Critical Access Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Church",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 3,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Not Available",
    "Mortality national comparison footnote":
      "Results are not available for this reporting period",
    "Safety of care national comparison": "Not Available",
    "Safety of care national comparison footnote":
      "Results are not available for this reporting period",
    "Readmission national comparison": "Same as the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Same as the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Same as the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison": "Not Available",
    "Efficient use of medical imaging national comparison footnote":
      "Results are not available for this reporting period",
  },
  {
    "Provider ID": "020024",
    "Hospital Name": "CENTRAL PENINSULA GENERAL HOSPITAL",
    Address: "250 HOSPITAL PLACE",
    City: "SOLDOTNA",
    State: "Alaska",
    "ZIP Code": 99669,
    "County Name": "",
    "Phone Number": 9072624404,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Other",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 3,
    "Booking date": "20 April 2024",
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Same as the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Same as the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Same as the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
];
export default mybookings;
